export const OBTENER_NEWS_TRENDING = "OBTENER_NEWS_TRENDING";
export const OBTENER_NEWS_TRENDING_EXITO = "OBTENER_NEWS_TRENDING_EXITO";
export const OBTENER_NEWS_TRENDING_ERROR = "OBTENER_NEWS_TRENDING_ERROR";

export const OBTENER_NEWS_BY_CATEGORY = "OBTENER_NEWS_BY_CATEGORY";
export const OBTENER_NEWS_BY_CATEGORY_EXITO = "OBTENER_NEWS_BY_CATEGORY_EXITO";
export const OBTENER_NEWS_BY_CATEGORY_ERROR = "OBTENER_NEWS_BY_CATEGORY_ERROR";

export const OBTENER_NEWS_BY_SEARCH = "OBTENER_NEWS_BY_SEARCH";
export const OBTENER_NEWS_BY_SEARCH_EXITO = "OBTENER_NEWS_BY_SEARCH_EXITO";
export const OBTENER_NEWS_BY_SEARCH_ERROR = "OBTENER_NEWS_BY_SEARCH_ERROR";

export const SET_PAGE_NUM = "SET_PAGE_NUM";
export const SET_PAGE_NUM_EXITO = "SET_PAGE_NUM_EXITO";
export const SET_PAGE_NUM_ERROR = "SET_PAGE_NUM_ERROR";